services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - "15672:15672"
    volumes:
      - "~/.billy/rabbitmq:/var/lib/rabbitmq"
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
    networks:
      - billy_network
    healthcheck:
      test: [ CMD, rabbitmqctl, status ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: billy
      POSTGRES_DB: billy
    networks:
      - billy_network
    volumes:
      - "~/.billy/postgres:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - billy_network
    restart: always
      

  billy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - billy_network
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped
    volumes:
      - ".:/app"

networks:
  billy_network:
    external: true