"""Add version changelog to notify users

Revision ID: 975eeba8a9f1
Revises: f2bd0a17dc78
Create Date: 2025-04-05 14:12:19.916669

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "975eeba8a9f1"
down_revision: Union[str, None] = "f2bd0a17dc78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("send_notification", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "user_account", sa.Column("last_version_notified", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "last_version_notified")
    op.drop_column("user_account", "send_notification")
    # ### end Alembic commands ###
